FROM alpine:3.15.0
LABEL org.opencontainers.image.source https://github.com/abatalev/dockerimages

RUN wget https://github.com/jgm/pandoc/releases/download/2.17.0.1/pandoc-2.17.0.1-linux-amd64.tar.gz
RUN tar xvzf pandoc-2.17.0.1-linux-amd64.tar.gz --strip-components 1 -C /usr/local
