FROM bellsoft/liberica-openjre-alpine-musl:17.0.3.1-2
LABEL org.opencontainers.image.description Liberica 17.0.3.1-2 with fonts
LABEL org.opencontainers.image.source https://github.com/abatalev/dockerimages
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f