FROM bellsoft/liberica-openjre-alpine-musl:8u333-2
LABEL org.opencontainers.image.description Liberica 8u333-2 with fonts
LABEL org.opencontainers.image.source https://github.com/abatalev/dockerimages
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts 
RUN fc-cache -f 
