FROM bellsoft/liberica-openjre-alpine-musl:11.0.14.1-1
LABEL org.opencontainers.image.description Liberica 11.0.14.1-1 with fonts
LABEL org.opencontainers.image.source https://github.com/abatalev/dockerimages
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f