FROM bellsoft/liberica-openjre-alpine-musl:8u322-6
LABEL org.opencontainers.image.description Liberica 8u322-6 with fonts
LABEL org.opencontainers.image.source https://github.com/abatalev/dockerimages
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts 
RUN fc-cache -f 
