FROM bellsoft/liberica-openjre-alpine-musl:21.0.1-12
LABEL org.opencontainers.image.description Liberica 21.0.1-12 with fonts
LABEL org.opencontainers.image.source https://github.com/abatalev/dockerimages
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f