FROM bellsoft/liberica-runtime-container:jre-17.0.13-musl
LABEL org.opencontainers.image.description="Liberica Runtime Container 17.0.13-12 with fonts"
LABEL org.opencontainers.image.source=https://github.com/abatalev/dockerimages
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f